#!/usr/bin/env bash

# lib/limit_speed.sh
#
# Module giới hạn băng thông cho Dante SOCKS5 proxy server
# Sử dụng Linux Traffic Control (tc) với HTB qdisc
# Tác giả: ThienTranJP
#
# Chức năng:
# - Giới hạn băng thông tổng thể cho Dante proxy
# - Giới hạn băng thông theo từng IP client
# - Đảm bảo công bằng giữa các user (fair queuing)
# - Tự động apply rules khi khởi động

# ==============================================================================
# CONSTANTS & CONFIG
# ==============================================================================

BANDWIDTH_CONFIG="/etc/dante/bandwidth.conf"
TC_SERVICE_FILE="/etc/systemd/system/dante-tc.service"
IFB_MODULE="ifb"

# Default values (có thể override từ config file)
DEFAULT_GLOBAL_RATE="100mbit"      # Tổng băng thông cho Dante
DEFAULT_GLOBAL_CEIL="100mbit"      # Ceiling (burst max)
DEFAULT_PER_IP_RATE="10mbit"       # Băng thông mỗi IP client
DEFAULT_PER_IP_CEIL="20mbit"       # Ceiling mỗi IP (cho phép burst)
DEFAULT_BURST="15k"                # Burst size

# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================

# Đọc cấu hình bandwidth từ file
load_bandwidth_config() {
    if [[ -f "$BANDWIDTH_CONFIG" ]]; then
        source "$BANDWIDTH_CONFIG"
    fi
    
    # Set defaults nếu chưa có
    GLOBAL_RATE="${GLOBAL_RATE:-$DEFAULT_GLOBAL_RATE}"
    GLOBAL_CEIL="${GLOBAL_CEIL:-$DEFAULT_GLOBAL_CEIL}"
    PER_IP_RATE="${PER_IP_RATE:-$DEFAULT_PER_IP_RATE}"
    PER_IP_CEIL="${PER_IP_CEIL:-$DEFAULT_PER_IP_CEIL}"
    BURST="${BURST:-$DEFAULT_BURST}"
    
    # Lấy interface từ Dante config nếu chưa set
    if [[ -z "$TC_INTERFACE" ]]; then
        TC_INTERFACE=$(ip -o -4 route show to default | awk '{print $5}')
    fi
}

# Lưu cấu hình bandwidth vào file
save_bandwidth_config() {
    ensure_proxy_dir
    
    cat > "$BANDWIDTH_CONFIG" << EOF
# Dante Bandwidth Configuration
# Generated by ProxyDante limit_speed.sh
# $(date)

# Network interface để áp dụng traffic control
TC_INTERFACE="$TC_INTERFACE"

# Giới hạn băng thông tổng thể cho Dante proxy
# Format: <number>kbit, <number>mbit, <number>gbit
GLOBAL_RATE="$GLOBAL_RATE"
GLOBAL_CEIL="$GLOBAL_CEIL"

# Giới hạn băng thông cho mỗi IP client
PER_IP_RATE="$PER_IP_RATE"
PER_IP_CEIL="$PER_IP_CEIL"

# Burst size (lượng data cho phép burst)
BURST="$BURST"

# Danh sách IP với giới hạn riêng (format: IP:RATE:CEIL)
# Ví dụ: CUSTOM_IP_LIMITS=("192.168.1.100:5mbit:10mbit" "192.168.1.101:20mbit:30mbit")
CUSTOM_IP_LIMITS=(${CUSTOM_IP_LIMITS[@]+"${CUSTOM_IP_LIMITS[@]}"})
EOF

    chmod 600 "$BANDWIDTH_CONFIG"
    success_message "Đã lưu cấu hình bandwidth vào $BANDWIDTH_CONFIG"
}

# Kiểm tra tc có sẵn không
check_tc_available() {
    if ! command -v tc >/dev/null 2>&1; then
        error_message "Không tìm thấy lệnh 'tc'. Đang cài đặt iproute2..."
        
        if [[ "$OStype" == "deb" || "$OStype" == "debian" || "$OStype" == "ubuntu" ]]; then
            apt-get update && apt-get install -y iproute2
        elif [[ "$OStype" == "centos" ]]; then
            yum install -y iproute
        fi
        
        if ! command -v tc >/dev/null 2>&1; then
            error_message "Không thể cài đặt tc. Vui lòng cài đặt thủ công."
            return 1
        fi
    fi
    return 0
}

# Lấy Dante port
get_dante_port_for_tc() {
    if [[ -f /etc/sockd.conf ]]; then
        grep -oP 'internal:.*port\s*=\s*\K[0-9]+' /etc/sockd.conf 2>/dev/null || echo "1080"
    else
        echo "1080"
    fi
}

# Chuyển đổi bandwidth string sang bytes/sec để hiển thị
bandwidth_to_human() {
    local bw="$1"
    echo "$bw"
}

# ==============================================================================
# TRAFFIC CONTROL FUNCTIONS
# ==============================================================================

# Xóa tất cả tc rules trên interface
clear_tc_rules() {
    local iface="$1"
    
    info_message "Xóa tc rules trên interface $iface..."
    
    # Xóa qdisc root (sẽ xóa tất cả rules)
    tc qdisc del dev "$iface" root 2>/dev/null || true
    tc qdisc del dev "$iface" ingress 2>/dev/null || true
    
    # Xóa IFB interface nếu có
    if ip link show ifb0 >/dev/null 2>&1; then
        tc qdisc del dev ifb0 root 2>/dev/null || true
        ip link set ifb0 down 2>/dev/null || true
    fi
    
    success_message "Đã xóa tc rules trên $iface"
}

# Thiết lập IFB (Intermediate Functional Block) cho ingress shaping
setup_ifb() {
    info_message "Thiết lập IFB interface cho ingress shaping..."
    
    # Load module ifb
    modprobe ifb numifbs=1 2>/dev/null || true
    
    # Bật ifb0
    ip link set ifb0 up 2>/dev/null || {
        warning_message "Không thể thiết lập IFB. Ingress shaping sẽ bị giới hạn."
        return 1
    }
    
    return 0
}

# Thiết lập HTB qdisc cho egress (upload từ server ra ngoài)
setup_egress_tc() {
    local iface="$1"
    local dante_port="$2"
    
    info_message "Thiết lập egress traffic control trên $iface..."
    
    # Tạo root qdisc với HTB
    tc qdisc add dev "$iface" root handle 1: htb default 30 || {
        error_message "Không thể tạo HTB qdisc trên $iface"
        return 1
    }
    
    # Class 1:1 - Root class với tổng băng thông
    tc class add dev "$iface" parent 1: classid 1:1 htb \
        rate "$GLOBAL_RATE" ceil "$GLOBAL_CEIL" burst "$BURST" || {
        error_message "Không thể tạo root class"
        return 1
    }
    
    # Class 1:10 - Dante proxy traffic (high priority)
    tc class add dev "$iface" parent 1:1 classid 1:10 htb \
        rate "$GLOBAL_RATE" ceil "$GLOBAL_CEIL" burst "$BURST" prio 1 || {
        error_message "Không thể tạo Dante class"
        return 1
    }
    
    # Class 1:20 - Per-IP default class
    tc class add dev "$iface" parent 1:10 classid 1:20 htb \
        rate "$PER_IP_RATE" ceil "$PER_IP_CEIL" burst "$BURST" prio 2 || {
        error_message "Không thể tạo per-IP default class"
        return 1
    }
    
    # Class 1:30 - Default/other traffic (lower priority)
    tc class add dev "$iface" parent 1:1 classid 1:30 htb \
        rate 1mbit ceil "$GLOBAL_CEIL" burst "$BURST" prio 3 || {
        error_message "Không thể tạo default class"
        return 1
    }
    
    # Filter: Dante traffic (source port = dante_port) vào class 1:10
    tc filter add dev "$iface" parent 1: protocol ip prio 1 u32 \
        match ip sport "$dante_port" 0xffff flowid 1:10 || {
        warning_message "Không thể tạo filter cho Dante port"
    }
    
    # Thêm SFQ (Stochastic Fair Queuing) để phân phối công bằng giữa các kết nối
    tc qdisc add dev "$iface" parent 1:10 handle 10: sfq perturb 10 || {
        warning_message "Không thể thêm SFQ qdisc"
    }
    
    tc qdisc add dev "$iface" parent 1:20 handle 20: sfq perturb 10 2>/dev/null || true
    tc qdisc add dev "$iface" parent 1:30 handle 30: sfq perturb 10 2>/dev/null || true
    
    success_message "Đã thiết lập egress traffic control"
    return 0
}

# Thiết lập ingress shaping (download về client qua proxy)
setup_ingress_tc() {
    local iface="$1"
    local dante_port="$2"
    
    info_message "Thiết lập ingress traffic control..."
    
    # Phương pháp: redirect ingress traffic sang IFB và shape ở đó
    if ! setup_ifb; then
        warning_message "Bỏ qua ingress shaping do không có IFB"
        return 1
    fi
    
    # Thêm ingress qdisc
    tc qdisc add dev "$iface" handle ffff: ingress || {
        warning_message "Không thể tạo ingress qdisc"
        return 1
    }
    
    # Redirect tất cả ingress traffic sang ifb0
    tc filter add dev "$iface" parent ffff: protocol ip u32 \
        match u32 0 0 action mirred egress redirect dev ifb0 || {
        warning_message "Không thể redirect traffic sang IFB"
        return 1
    }
    
    # Thiết lập HTB trên ifb0 (giống egress)
    tc qdisc add dev ifb0 root handle 1: htb default 30 || {
        warning_message "Không thể tạo HTB qdisc trên ifb0"
        return 1
    }
    
    tc class add dev ifb0 parent 1: classid 1:1 htb \
        rate "$GLOBAL_RATE" ceil "$GLOBAL_CEIL" burst "$BURST"
    
    tc class add dev ifb0 parent 1:1 classid 1:10 htb \
        rate "$GLOBAL_RATE" ceil "$GLOBAL_CEIL" burst "$BURST" prio 1
    
    tc class add dev ifb0 parent 1:10 classid 1:20 htb \
        rate "$PER_IP_RATE" ceil "$PER_IP_CEIL" burst "$BURST" prio 2
    
    # Filter cho Dante traffic (destination port = dante_port)
    tc filter add dev ifb0 parent 1: protocol ip prio 1 u32 \
        match ip dport "$dante_port" 0xffff flowid 1:10
    
    # SFQ cho fair queuing
    tc qdisc add dev ifb0 parent 1:10 handle 10: sfq perturb 10 2>/dev/null || true
    
    success_message "Đã thiết lập ingress traffic control"
    return 0
}

# ==============================================================================
# PER-IP BANDWIDTH LIMITING
# ==============================================================================

# Thêm giới hạn băng thông cho một IP cụ thể
add_ip_bandwidth_limit() {
    local ip="$1"
    local rate="$2"
    local ceil="${3:-$rate}"
    local iface="$TC_INTERFACE"
    
    if [[ -z "$ip" || -z "$rate" ]]; then
        error_message "Thiếu tham số: add_ip_bandwidth_limit <IP> <RATE> [CEIL]"
        return 1
    fi
    
    # Tạo class ID từ IP (hash đơn giản)
    local ip_hash=$(echo "$ip" | md5sum | cut -c1-4)
    local class_id=$((16#$ip_hash % 900 + 100))  # Range 100-999
    
    info_message "Thêm giới hạn $rate (ceil: $ceil) cho IP $ip (class 1:$class_id)..."
    
    # Tạo class cho IP này
    tc class add dev "$iface" parent 1:10 classid 1:$class_id htb \
        rate "$rate" ceil "$ceil" burst "$BURST" prio 2 2>/dev/null || {
        # Nếu đã tồn tại, thử thay đổi
        tc class change dev "$iface" parent 1:10 classid 1:$class_id htb \
            rate "$rate" ceil "$ceil" burst "$BURST" prio 2 || {
            error_message "Không thể tạo/cập nhật class cho IP $ip"
            return 1
        }
    }
    
    # Filter traffic từ IP này vào class
    tc filter add dev "$iface" parent 1: protocol ip prio 10 u32 \
        match ip dst "$ip" flowid 1:$class_id 2>/dev/null || true
    
    # Làm tương tự cho ifb0 (ingress)
    if ip link show ifb0 >/dev/null 2>&1; then
        tc class add dev ifb0 parent 1:10 classid 1:$class_id htb \
            rate "$rate" ceil "$ceil" burst "$BURST" prio 2 2>/dev/null || \
        tc class change dev ifb0 parent 1:10 classid 1:$class_id htb \
            rate "$rate" ceil "$ceil" burst "$BURST" prio 2 2>/dev/null || true
        
        tc filter add dev ifb0 parent 1: protocol ip prio 10 u32 \
            match ip src "$ip" flowid 1:$class_id 2>/dev/null || true
    fi
    
    # Lưu vào config
    local found=0
    for i in "${!CUSTOM_IP_LIMITS[@]}"; do
        if [[ "${CUSTOM_IP_LIMITS[$i]}" == "$ip:"* ]]; then
            CUSTOM_IP_LIMITS[$i]="$ip:$rate:$ceil"
            found=1
            break
        fi
    done
    
    if [[ $found -eq 0 ]]; then
        CUSTOM_IP_LIMITS+=("$ip:$rate:$ceil")
    fi
    
    save_bandwidth_config
    success_message "Đã thêm giới hạn băng thông cho IP $ip: $rate (ceil: $ceil)"
}

# Xóa giới hạn băng thông cho một IP
remove_ip_bandwidth_limit() {
    local ip="$1"
    local iface="$TC_INTERFACE"
    
    if [[ -z "$ip" ]]; then
        error_message "Thiếu tham số: remove_ip_bandwidth_limit <IP>"
        return 1
    fi
    
    local ip_hash=$(echo "$ip" | md5sum | cut -c1-4)
    local class_id=$((16#$ip_hash % 900 + 100))
    
    info_message "Xóa giới hạn băng thông cho IP $ip..."
    
    # Xóa filter và class
    tc filter del dev "$iface" parent 1: protocol ip prio 10 u32 \
        match ip dst "$ip" 2>/dev/null || true
    tc class del dev "$iface" classid 1:$class_id 2>/dev/null || true
    
    # Xóa trên ifb0
    tc filter del dev ifb0 parent 1: protocol ip prio 10 u32 \
        match ip src "$ip" 2>/dev/null || true
    tc class del dev ifb0 classid 1:$class_id 2>/dev/null || true
    
    # Xóa khỏi config
    local new_limits=()
    for limit in "${CUSTOM_IP_LIMITS[@]}"; do
        if [[ "$limit" != "$ip:"* ]]; then
            new_limits+=("$limit")
        fi
    done
    CUSTOM_IP_LIMITS=("${new_limits[@]}")
    
    save_bandwidth_config
    success_message "Đã xóa giới hạn băng thông cho IP $ip"
}

# ==============================================================================
# MAIN CONTROL FUNCTIONS
# ==============================================================================

# Thiết lập traffic control hoàn chỉnh
setup_traffic_control() {
    info_message "Bắt đầu thiết lập Traffic Control..."
    
    # Kiểm tra tc
    check_tc_available || return 1
    
    # Load config
    load_bandwidth_config
    
    local dante_port=$(get_dante_port_for_tc)
    
    info_message "Interface: $TC_INTERFACE"
    info_message "Dante port: $dante_port"
    info_message "Global rate: $GLOBAL_RATE (ceil: $GLOBAL_CEIL)"
    info_message "Per-IP rate: $PER_IP_RATE (ceil: $PER_IP_CEIL)"
    
    # Xóa rules cũ
    clear_tc_rules "$TC_INTERFACE"
    
    # Thiết lập egress
    setup_egress_tc "$TC_INTERFACE" "$dante_port" || {
        error_message "Không thể thiết lập egress traffic control"
        return 1
    }
    
    # Thiết lập ingress
    setup_ingress_tc "$TC_INTERFACE" "$dante_port" || {
        warning_message "Ingress shaping không khả dụng, chỉ có egress shaping"
    }
    
    # Áp dụng custom IP limits
    if [[ ${#CUSTOM_IP_LIMITS[@]} -gt 0 ]]; then
        info_message "Áp dụng ${#CUSTOM_IP_LIMITS[@]} custom IP limits..."
        for limit in "${CUSTOM_IP_LIMITS[@]}"; do
            local ip=$(echo "$limit" | cut -d: -f1)
            local rate=$(echo "$limit" | cut -d: -f2)
            local ceil=$(echo "$limit" | cut -d: -f3)
            add_ip_bandwidth_limit "$ip" "$rate" "$ceil"
        done
    fi
    
    success_message "Đã thiết lập Traffic Control thành công!"
    echo ""
    show_current_limits
}

# Xóa toàn bộ traffic control
remove_traffic_control() {
    info_message "Xóa toàn bộ Traffic Control..."
    
    load_bandwidth_config
    
    clear_tc_rules "$TC_INTERFACE"
    
    # Xóa IFB
    if ip link show ifb0 >/dev/null 2>&1; then
        ip link set ifb0 down 2>/dev/null || true
    fi
    
    success_message "Đã xóa toàn bộ Traffic Control"
}

# Hiển thị trạng thái hiện tại
show_current_limits() {
    load_bandwidth_config
    
    echo ""
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
    echo -e "${GREEN}           TRẠNG THÁI BANDWIDTH LIMITING               ${NC}"
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
    echo ""
    
    echo -e "${YELLOW}[Cấu hình hiện tại]${NC}"
    echo "  Interface:      $TC_INTERFACE"
    echo "  Global Rate:    $GLOBAL_RATE"
    echo "  Global Ceil:    $GLOBAL_CEIL"
    echo "  Per-IP Rate:    $PER_IP_RATE"
    echo "  Per-IP Ceil:    $PER_IP_CEIL"
    echo ""
    
    if [[ ${#CUSTOM_IP_LIMITS[@]} -gt 0 ]]; then
        echo -e "${YELLOW}[Custom IP Limits]${NC}"
        for limit in "${CUSTOM_IP_LIMITS[@]}"; do
            local ip=$(echo "$limit" | cut -d: -f1)
            local rate=$(echo "$limit" | cut -d: -f2)
            local ceil=$(echo "$limit" | cut -d: -f3)
            echo "  $ip: rate=$rate, ceil=$ceil"
        done
        echo ""
    fi
    
    echo -e "${YELLOW}[TC Qdisc trên $TC_INTERFACE]${NC}"
    tc qdisc show dev "$TC_INTERFACE" 2>/dev/null || echo "  (không có qdisc)"
    echo ""
    
    echo -e "${YELLOW}[TC Classes trên $TC_INTERFACE]${NC}"
    tc class show dev "$TC_INTERFACE" 2>/dev/null || echo "  (không có class)"
    echo ""
    
    if ip link show ifb0 >/dev/null 2>&1; then
        echo -e "${YELLOW}[TC trên IFB0 (ingress)]${NC}"
        tc class show dev ifb0 2>/dev/null || echo "  (không có class)"
        echo ""
    fi
    
    echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
}

# Hiển thị thống kê realtime
show_traffic_stats() {
    load_bandwidth_config
    
    echo ""
    echo -e "${BLUE}Traffic Statistics (nhấn Ctrl+C để thoát)${NC}"
    echo ""
    
    while true; do
        clear
        echo -e "${GREEN}=== Traffic Statistics ===${NC}"
        echo "Thời gian: $(date)"
        echo ""
        
        echo -e "${YELLOW}[Egress - $TC_INTERFACE]${NC}"
        tc -s class show dev "$TC_INTERFACE" 2>/dev/null | head -30
        echo ""
        
        if ip link show ifb0 >/dev/null 2>&1; then
            echo -e "${YELLOW}[Ingress - ifb0]${NC}"
            tc -s class show dev ifb0 2>/dev/null | head -30
        fi
        
        sleep 2
    done
}

# ==============================================================================
# SYSTEMD SERVICE
# ==============================================================================

# Tạo systemd service để apply tc rules khi boot
create_tc_service() {
    info_message "Tạo systemd service cho Traffic Control..."
    
    local script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    
    cat > "$TC_SERVICE_FILE" << EOF
[Unit]
Description=Dante Proxy Traffic Control
After=network.target sockd.service
Wants=sockd.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'source $script_path/common.sh && source $script_path/limit_speed.sh && setup_traffic_control'
ExecStop=/bin/bash -c 'source $script_path/common.sh && source $script_path/limit_speed.sh && remove_traffic_control'

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable dante-tc.service
    
    success_message "Đã tạo và enable dante-tc.service"
    info_message "TC rules sẽ tự động áp dụng khi khởi động"
}

# Xóa systemd service
remove_tc_service() {
    info_message "Xóa systemd service cho Traffic Control..."
    
    systemctl stop dante-tc.service 2>/dev/null || true
    systemctl disable dante-tc.service 2>/dev/null || true
    rm -f "$TC_SERVICE_FILE"
    systemctl daemon-reload
    
    success_message "Đã xóa dante-tc.service"
}

# ==============================================================================
# INTERACTIVE MENU
# ==============================================================================

# Menu thay đổi giới hạn tốc độ
change_speed_limit() {
    load_bandwidth_config
    
    while true; do
        echo ""
        echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
        echo -e "${GREEN}         QUẢN LÝ GIỚI HẠN BĂNG THÔNG PROXY             ${NC}"
        echo -e "${BLUE}═══════════════════════════════════════════════════════${NC}"
        echo ""
        echo -e "${CYAN}  1)${NC} Xem trạng thái hiện tại"
        echo -e "${CYAN}  2)${NC} Thiết lập/Cập nhật Traffic Control"
        echo -e "${CYAN}  3)${NC} Thay đổi giới hạn tổng thể (Global)"
        echo -e "${CYAN}  4)${NC} Thay đổi giới hạn mặc định mỗi IP"
        echo -e "${CYAN}  5)${NC} Thêm giới hạn riêng cho một IP"
        echo -e "${CYAN}  6)${NC} Xóa giới hạn riêng của một IP"
        echo -e "${CYAN}  7)${NC} Xem thống kê traffic realtime"
        echo -e "${CYAN}  8)${NC} Xóa toàn bộ Traffic Control"
        echo -e "${CYAN}  9)${NC} Bật/Tắt tự động apply khi khởi động"
        echo -e "${CYAN} 10)${NC} Quay lại menu chính"
        echo ""
        
        read -p "Chọn một tùy chọn [1-10]: " option
        
        case $option in
            1)
                show_current_limits
                pause
                ;;
            2)
                setup_traffic_control
                pause
                ;;
            3)
                echo ""
                echo "Giới hạn tổng thể hiện tại: $GLOBAL_RATE (ceil: $GLOBAL_CEIL)"
                read -p "Nhập rate mới (vd: 100mbit, 1gbit): " -e -i "$GLOBAL_RATE" new_rate
                read -p "Nhập ceil mới (vd: 100mbit, 1gbit): " -e -i "$GLOBAL_CEIL" new_ceil
                
                if [[ -n "$new_rate" ]]; then
                    GLOBAL_RATE="$new_rate"
                    GLOBAL_CEIL="${new_ceil:-$new_rate}"
                    save_bandwidth_config
                    
                    read -p "Áp dụng ngay? (y/n): " -e -i y apply
                    if [[ "$apply" == "y" || "$apply" == "Y" ]]; then
                        setup_traffic_control
                    fi
                fi
                pause
                ;;
            4)
                echo ""
                echo "Giới hạn mỗi IP hiện tại: $PER_IP_RATE (ceil: $PER_IP_CEIL)"
                read -p "Nhập rate mới cho mỗi IP (vd: 10mbit): " -e -i "$PER_IP_RATE" new_rate
                read -p "Nhập ceil mới cho mỗi IP (vd: 20mbit): " -e -i "$PER_IP_CEIL" new_ceil
                
                if [[ -n "$new_rate" ]]; then
                    PER_IP_RATE="$new_rate"
                    PER_IP_CEIL="${new_ceil:-$new_rate}"
                    save_bandwidth_config
                    
                    read -p "Áp dụng ngay? (y/n): " -e -i y apply
                    if [[ "$apply" == "y" || "$apply" == "Y" ]]; then
                        setup_traffic_control
                    fi
                fi
                pause
                ;;
            5)
                echo ""
                read -p "Nhập địa chỉ IP client: " ip_addr
                
                if [[ -z "$ip_addr" ]]; then
                    error_message "IP không được để trống"
                else
                    read -p "Nhập rate cho IP này (vd: 5mbit): " ip_rate
                    read -p "Nhập ceil cho IP này (vd: 10mbit): " -e -i "$ip_rate" ip_ceil
                    
                    if [[ -n "$ip_rate" ]]; then
                        add_ip_bandwidth_limit "$ip_addr" "$ip_rate" "$ip_ceil"
                    fi
                fi
                pause
                ;;
            6)
                echo ""
                if [[ ${#CUSTOM_IP_LIMITS[@]} -eq 0 ]]; then
                    warning_message "Không có IP nào có giới hạn riêng"
                else
                    echo "Danh sách IP có giới hạn riêng:"
                    for limit in "${CUSTOM_IP_LIMITS[@]}"; do
                        echo "  - $limit"
                    done
                    echo ""
                    read -p "Nhập IP cần xóa giới hạn: " ip_addr
                    
                    if [[ -n "$ip_addr" ]]; then
                        remove_ip_bandwidth_limit "$ip_addr"
                    fi
                fi
                pause
                ;;
            7)
                show_traffic_stats
                ;;
            8)
                read -p "Bạn có chắc muốn xóa toàn bộ Traffic Control? (y/n): " confirm
                if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
                    remove_traffic_control
                fi
                pause
                ;;
            9)
                if systemctl is-enabled dante-tc.service >/dev/null 2>&1; then
                    echo "dante-tc.service đang được ENABLE"
                    read -p "Bạn muốn DISABLE? (y/n): " confirm
                    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
                        remove_tc_service
                    fi
                else
                    echo "dante-tc.service chưa được tạo hoặc đang DISABLE"
                    read -p "Bạn muốn tạo và ENABLE? (y/n): " confirm
                    if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
                        create_tc_service
                    fi
                fi
                pause
                ;;
            10)
                return 0
                ;;
            *)
                error_message "Lựa chọn không hợp lệ"
                pause
                ;;
        esac
    done
}
